// nuxt.config.ts
// Unified config generated by merger
import { defineNuxtConfig } from 'nuxt/config'

export default defineNuxtConfig({
  modules: [
    '@pinia/nuxt',
    '@nuxtjs/tailwindcss'
  ],
  runtimeConfig: {
    // server-side private
    apiSecret: process.env.API_SECRET || '',
    public: {
      apiBase: process.env.NUXT_PUBLIC_API_BASE || 'http://localhost:4000',
      wsBase: process.env.NUXT_PUBLIC_WS_BASE || 'ws://localhost:4000/socket'
    }
  },
  nitro: {
    preset: process.env.NITRO_PRESET
  },
  routeRules: {
    // cache rules can be adjusted here
  },
  typescript: { strict: true }
})
