// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 28/8/2025, 11.47.34
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/AIRNAV/Gabungan/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/AIRNAV/Gabungan/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/AIRNAV/Gabungan/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/AIRNAV/Gabungan/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/AIRNAV/Gabungan/plugins/**/*.{js,ts,mjs}","C:/AIRNAV/Gabungan/composables/**/*.{js,ts,mjs}","C:/AIRNAV/Gabungan/utils/**/*.{js,ts,mjs}","C:/AIRNAV/Gabungan/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/AIRNAV/Gabungan/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/AIRNAV/Gabungan/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/AIRNAV/Gabungan/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;